 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - name: gitartwork on contribution graph
         uses: jasineri/gitartwork@v1
       - uses: actions/checkout@v3
       - uses: jasineri/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: Pritam0077
            # Text on contribution graph 
            text: Pritam
       - uses: jasineri/simple-push-action@v1
